sysbuild: symbol for Infuse Bluetooth controllers
Add a dedicated symbol for Bluetooth controllers so the appropriate
Infuse snippet can be applied.

Signed-off-by: Jordan Yates <jordan@embeint.com>